# Generated by Django 4.0.4 on 2022-04-16 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='catch_phrase',
            field=models.CharField(default='about', max_length=255),
        ),
        migrations.AddField(
            model_name='super',
            name='super_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='super_types.super_type'),
            preserve_default=False,
        ),
    ]
