# Generated by Django 4.0.4 on 2022-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_super_catch_phrase_super_super_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='catch_phrase',
        ),
        migrations.AddField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
